# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [ ]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))

while(True):
    d = int(input("Insert the dimension of matrix: "))
    if d > 0:
        break
    else:
        print("Insert a positive number.")

matrixrand1 = random_matrix(d)

def permutation_list(dim):
    """ 
    The function creates a permutation list 
    """
    p = list(itertools.permutations(range(0, dim), dim))
    return p

print(permutation_list(d))


def product_multpl(matrixrand1, perm1):
    """
    The function calculates multiplication of the product of given elements of the matrix
    """
    prod = 1
    for i in range(len(matrixrand1)):
        prod *= matrixrand1[i][perm1[i]]
    return prod

def sum_product(matrixrand1):
    """ 
    The function indicates the sign of each multiplication and finds the determinant
    """
    

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]
[[7 9 1]
 [1 3 5]
 [3 3 1]]


UnboundLocalError: cannot access local variable 'sign' where it is not associated with a value